[package]
name = "spl-zk-token"
description = "Solana Program Library Confidential Token"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/solana-labs/solana-program-library"
version = "0.1.0"
edition = "2018"
publish = false

[dependencies]
bytemuck = "1.7.2"
bytemuck_derive = "1.0.1"
num-derive = "0.3"
num-traits = "0.2"
solana-program = "=1.7.11"
spl-token = { version = "3.2.0", features = ["no-entrypoint"] }
zeroable = "0.2.0"
getrandom = { version = "0.1", features = ["dummy"] }

[features]
test-bpf = []

[dev-dependencies]
assert_matches = "1.4.0"
solana-program-test = "=1.7.11"
solana-sdk = "=1.7.11"
solana-validator = "=1.7.11"

[lib]
crate-type = ["cdylib", "lib"]
